### ISSUE TITLE
OrderedDict in error metrics?

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/ldcpy#11]
It would be nice if `print_stats()` printed out statistics in the same order every time; I think using an `OrderedDict` underneath the json will accomplish that.

**Comment by andersy005** [comment]
Another cool tool for printing dictionaries or json-like objects is the [pprint](https://docs.python.org/3/library/pprint.html) module in Python.

**Comment by allibco** [comment]
agree - it would better if always in the same order

**Comment by pinarda** [comment]
requires 

- [ ] #39
