### ISSUE TITLE
error plotting in largegladenotebook

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#118]
ldcpy.plot(ds_PS, "PS", set1='orig', metric='mean', plot_type="time_series", 
           set2="lossy", group_by="time.month", metric_type="diff")

 I am wondering if the issue is that this data set is monthly (not daily)...

**Comment by allibco** [comment]
Here's the error message:
IndexError                                Traceback (most recent call last)
<ipython-input-16-bb4f07931858> in <module>
      1 # Time-series plot of mean PS differences between ds_PS orig and ds_PS lossy datasets grouped by month of year
----> 2 ldcpy.plot(ds_PS, "PS", set1='orig', metric='mean', plot_type="time_series", set2="lossy", group_by="time.month", metric_type="diff")

~/repos/ldcpy/ldcpy/plot.py in plot(ds, varname, metric, set1, set2, group_by, scale, metric_type, plot_type, transform, subset, lat, lon, lev, color, standardized_err, quantile, start, end)
    709         mp.spatial_plot(plot_data_set1, title_set1)
    710     elif plot_type == 'time_series':
--> 711         mp.time_series_plot(plot_data_set1, title_set1)
    712     elif plot_type == 'histogram':
    713         mp.hist_plot(plot_data_set1, title_set1)

~/repos/ldcpy/ldcpy/plot.py in time_series_plot(self, da, title)
    419             # no_hyphen_int_labels = [(int(float(re.sub('−', '-', label)))) for label in int_labels]
    420             month_labels = [
--> 421                 calendar.month_name[i] if calendar.month_name[i] != '' else '' for i in int_labels
    422             ]
    423             unique_month_labels = list(dict.fromkeys(month_labels))

~/repos/ldcpy/ldcpy/plot.py in <listcomp>(.0)
    419             # no_hyphen_int_labels = [(int(float(re.sub('−', '-', label)))) for label in int_labels]
    420             month_labels = [
--> 421                 calendar.month_name[i] if calendar.month_name[i] != '' else '' for i in int_labels
    422             ]
    423             unique_month_labels = list(dict.fromkeys(month_labels))

/ncar/usr/jupyterhub/envs/cmip6-201910/lib/python3.7/calendar.py in __getitem__(self, i)
     57 
     58     def __getitem__(self, i):
---> 59         funcs = self._months[i]
     60         if isinstance(i, slice):
     61             return [f(self.format) for f in funcs]

IndexError: list index out of range

**Comment by pinarda** [comment]
plot.py line 731 - in the LargeDatasetNotebook the metric_name_set2 is not set before it is called in line 753

**Comment by pinarda** [comment]
still need to troubleshoot the problem with the spatial_comparison plots, the rest is fixed.

**Comment by pinarda** [comment]
@allibco Can you check and make sure these errors are still occurring when you get the chance? I fixed both of these issues with the same data on my local machine, but for some reason they come right back when I test them on Casper (and I have triple checked that everything is up to date on Casper). It's unlikely to work but I am running out of ideas.

**Comment by allibco** [comment]
Yes, I will check - but not until tomorrow :)

**Comment by pinarda** [comment]
Oh, I think it was importing ldcpy from your home directory, not mine. That would explain it.
