### ISSUE TITLE
Figure out what's lazy and what's not in dask

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#125]
we can't use the xarray.values property (it will block) - use .data instead
the drop=True subset may also block

in zscore_percent_significant
scipy stats - may not be lazy
also see if np.array() forces to a numpy array

**Comment by allibco** [comment]
I doesn't appear that using "values" in the compare_stats is problematic as these arrays are all size 1.  I tried it on jupyter hub and it seems fine in terms of speed.  Also I'm not sure how to get what we want from ".data." - that gives a dask data array with ndim = 0 and I can't seem to get the value out...

**Comment by allibco** [comment]
OK, I've been working on this for a while and I knew if I submitted a comment about not bring able to get the info from data that I's figure it out :).   You have to do y.data then y.compute() instead of y.values.

I don't think this will necessarily speed things up, but I will try it!

**Comment by allibco** [comment]
git rid of values in util.py.  This doesn't affect the speed as we needed to compute then anyhow, my it does may it more dask-friendly :)

**Comment by pinarda** [comment]
I am still unable to use to dask dashboard today, but I managed to generate this a couple days ago showing the performance during a single plot function. 

It looks a little bit different than the performance report, in particular there are more workers, and it looks like open_datasets is running entirely in the beginning, whereas my dashboard was showing open_datasets running right before a mean chunk was computed (which made more sense to me). But you can see the spaces and a lot of red tasks indicating communication overhead between workers.

[dask-report.html.zip](https://github.com/NCAR/ldcpy/files/5143501/dask-report.html.zip)

<img width="1024" alt="Screen Shot 2020-08-28 at 11 56 09 AM" src="https://user-images.githubusercontent.com/2608326/91601309-a84eff80-e926-11ea-9781-fe1d48344dee.png">

**Comment by allibco** [comment]
can this be closed?

**Comment by allibco** [comment]
Can this be closed? @andersy005 @pinarda
