### ISSUE TITLE
have notebooks and package available on glade

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#129]
Put in documentation about how to launch a job and open /find notebook on Jupyter hub...

**Comment by allibco** [comment]
Anderson can add ldcpy to the cmip6-2019-10 kernel when we are ready

**Comment by pinarda** [comment]
see if #115 can solve this issue, we don't want anyone to edit the public copy and mess it up for everyone else.

**Comment by allibco** [comment]
using binder now instead
