### ISSUE TITLE
change the package name

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#147]

**Comment by allibco** [comment]
Some suggestions (some more serious than others...) so we can keep ldcpy....

Lo! Data Comparison!
Lotsa Data Comparison
Large Data Comparison
Likeness Data Comparison
statisticaL Data Comparison
equaLity Data Comparison

**Comment by pinarda** [comment]
I like large! I feel like it's a little bit more general than what we are doing right now, but I don't its currently worth changing the name over.

**Comment by allibco** [comment]
I agree that let's pick something to keep ldcpy acronym

**Comment by allibco** [comment]
update documentation
