### ISSUE TITLE
weird tick message

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#166]
ach day of the year (our data consists of 100 days).

1
# Time-series plot of TS mean in ds orig dataset
2
ldcpy.plot(col_ds, "TS", sets=['orig'], metric='mean', plot_type="time_series")
 ConversionError: Failed to convert value(s) to axis units: array([cftime.DatetimeNoLeap(1920, 1, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 29, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 30, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 31, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 29, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 30, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 31, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 10, 0, 0, 0, 0)], dtype=object) 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axis.py in convert_units(self, x)
   1572         try:
-> 1573             ret = self.converter.convert(x, self.units, self)
   1574         except Exception as e:

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/dates.py in convert(value, unit, axis)
   1920         """
-> 1921         return date2num(value)
   1922 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/dates.py in date2num(d)
    436             return d
--> 437         return _to_ordinalf_np_vectorized(d)
    438 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/numpy/lib/function_base.py in __call__(self, *args, **kwargs)
   2090 
-> 2091         return self._vectorize_call(func=func, args=vargs)
   2092 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/numpy/lib/function_base.py in _vectorize_call(self, func, args)
   2160         else:
-> 2161             ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
   2162 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/numpy/lib/function_base.py in _get_ufunc_and_otypes(self, func, args)
   2120             inputs = [arg.flat[0] for arg in args]
-> 2121             outputs = func(*inputs)
   2122 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/dates.py in _to_ordinalf(dt)
    221 
--> 222     base = float(dt.toordinal())
    223 

AttributeError: 'cftime._cftime.DatetimeNoLeap' object has no attribute 'toordinal'

The above exception was the direct cause of the following exception:

ConversionError                           Traceback (most recent call last)
<ipython-input-21-232c1c2c16e3> in <module>
      1 # Time-series plot of TS mean in ds orig dataset
----> 2 ldcpy.plot(col_ds, "TS", sets=['orig'], metric='mean', plot_type="time_series")

~/alli/code-repo/ldcpy/ldcpy/plot.py in plot(ds, varname, metric, sets, group_by, scale, metric_type, plot_type, transform, subset, lat, lon, lev, color, standardized_err, quantile, start, end, calc_ssim)
    715         mp.spatial_plot(plot_dataset, titles)
    716     elif plot_type == 'time_series':
--> 717         mp.time_series_plot(plot_dataset, titles)
    718     elif plot_type == 'histogram':
    719         mp.hist_plot(plot_dataset, titles)

~/alli/code-repo/ldcpy/ldcpy/plot.py in time_series_plot(self, da_sets, titles)
    427                 da_sets[i]['time'] = dtindex
    428 
--> 429                 mpl.pyplot.plot_date(
    430                     da_sets[i].time.data, da_sets[i], f'C{i}', label=f'{da_sets.sets.data[i]}'
    431                 )

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/pyplot.py in plot_date(x, y, fmt, tz, xdate, ydate, data, **kwargs)
   2769         x, y, fmt='o', tz=None, xdate=True, ydate=False, *,
   2770         data=None, **kwargs):
-> 2771     return gca().plot_date(
   2772         x, y, fmt=fmt, tz=tz, xdate=xdate, ydate=ydate, **({"data":
   2773         data} if data is not None else {}), **kwargs)

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/__init__.py in inner(ax, data, *args, **kwargs)
   1563     def inner(ax, *args, data=None, **kwargs):
   1564         if data is None:
-> 1565             return func(ax, *map(sanitize_sequence, args), **kwargs)
   1566 
   1567         bound = new_sig.bind(ax, *args, **kwargs)

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py in plot_date(self, x, y, fmt, tz, xdate, ydate, **kwargs)
   1719             self.yaxis_date(tz)
   1720 
-> 1721         ret = self.plot(x, y, fmt, **kwargs)
   1722 
   1723         self._request_autoscale_view()

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axes/_axes.py in plot(self, scalex, scaley, data, *args, **kwargs)
   1647         lines = [*self._get_lines(*args, data=data, **kwargs)]
   1648         for line in lines:
-> 1649             self.add_line(line)
   1650         self._request_autoscale_view(scalex=scalex, scaley=scaley)
   1651         return lines

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axes/_base.py in add_line(self, line)
   1848             line.set_clip_path(self.patch)
   1849 
-> 1850         self._update_line_limits(line)
   1851         if not line.get_label():
   1852             line.set_label('_line%d' % len(self.lines))

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axes/_base.py in _update_line_limits(self, line)
   1870         Figures out the data limit of the given line, updating self.dataLim.
   1871         """
-> 1872         path = line.get_path()
   1873         if path.vertices.size == 0:
   1874             return

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/lines.py in get_path(self)
   1025         """
   1026         if self._invalidy or self._invalidx:
-> 1027             self.recache()
   1028         return self._path
   1029 

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/lines.py in recache(self, always)
    667     def recache(self, always=False):
    668         if always or self._invalidx:
--> 669             xconv = self.convert_xunits(self._xorig)
    670             x = _to_unmasked_float_array(xconv).ravel()
    671         else:

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/artist.py in convert_xunits(self, x)
    176         if ax is None or ax.xaxis is None:
    177             return x
--> 178         return ax.xaxis.convert_units(x)
    179 
    180     def convert_yunits(self, y):

~/anaconda3/envs/ldcpy_dev/lib/python3.8/site-packages/matplotlib/axis.py in convert_units(self, x)
   1573             ret = self.converter.convert(x, self.units, self)
   1574         except Exception as e:
-> 1575             raise munits.ConversionError('Failed to convert value(s) to axis '
   1576                                          f'units: {x!r}') from e
   1577         return ret

ConversionError: Failed to convert value(s) to axis units: array([cftime.DatetimeNoLeap(1920, 1, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 29, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 30, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 1, 31, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 2, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 10, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 11, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 12, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 13, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 14, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 15, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 16, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 18, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 19, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 20, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 21, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 22, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 23, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 24, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 25, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 26, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 27, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 28, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 29, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 30, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 3, 31, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 1, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 2, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 3, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 4, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 5, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 6, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 7, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 8, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 9, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1920, 4, 10, 0, 0, 0, 0)], dtype=object)

Locator attempting to generate 3654 ticks ([730120.0, ..., 733773.0]), which exceeds Locator.MAXTICKS (1000).
Locator attempting to generate 3654 ticks ([730120.0, ..., 733773.0]), which exceeds Locator.MAXTICKS (1000).
Locator attempting to generate 3654 ticks ([730120.0, ..., 733773.0]), which exceeds Locator.MAXT

**Comment by pinarda** [comment]
I have been unable to recreate this issue so far, and the tests are running fine on CircleCI so I might need your help to debug this one.



I did try to update conda to make sure everything was consistent, but I am currently unable to because of this strange issue with the cartopy version in the base environment (I can't do anything with the package, including removing it, without getting this error). I think the easiest option might be to create an entirely new base environment but I think I may need a fresh conda install to do that:

alex$ conda upgrade -n base conda
Collecting package metadata (current_repodata.json): failed

InvalidVersionSpec: Invalid version '0.18.1.dev28-': empty version component

**Comment by pinarda** [comment]
Any idea what the values [730120.0, ..., 733773.0] represent?

**Comment by allibco** [comment]
OK, I will try to sort this out!

**Comment by allibco** [comment]
@pinarda 

OK, i've been working on this for hours and can't get it working.  The only thing I can think of at this point is to put in a default 'group_by' if the user doesn't specify a group_by since that would work.

I did figure out that we can suppress the warning error with:
 dtindex = da_sets[i].indexes['time'].to_datetimeindex(unsafe=True)
(but that doesn't fix the ticks issue..)

I tried to use 
dt_index = cftime.num2pydate(da_sets[i].indexes['time'], units, calendar='365_day')
to get rid of the warning and possibly tick issue, but it is unclear how to set units..it should be something like
units = "days since 1920-01-01 00:00:00"
but it's not working....
