### ISSUE TITLE
save plot option

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#168]
Add an option to the plot command to write out the figure to a file

**Comment by pinarda** [comment]
I don't think we need a function for this. This is as simple as saving it using matplotlib:

```
import matplotlib.pyplot as plt
ldcpy.plot(col_ds, "TS", sets=["orig"], start=0, end=1, calc="mean")
plt.savefig(f"MYFIGURE.png", bbox_inches='tight')
```

**Comment by pinarda** [comment]
I added these commands to the first plot in the tutorial notebook for reference.
