### ISSUE TITLE
compare_stats formatting

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#169]
Needs improvement.  Better formatting - maybe some color? (Dorit's suggestion)

**Comment by andersy005** [comment]
If you want do add some color to the formatting, I recommend looking into putting the computed stats in a Pandas DataFrame and using Pandas DataFrame styling (https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html) to add some color. 

Another option worth looking into is the **rich** package: https://github.com/willmcgugan/rich. Rich is for terminal based formatting though... I don't know how it works in notebooks.
