### ISSUE TITLE
Miscellaneous list of performance improvements

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#188]
Code cleanup:
remove any unneeded libraries (do we need xfrt or can we use xr.fft()?)
add options to selected metrics:
    add ns/ew option to contrast variance instead of using two difference metrics
    add deseas/first_difference option to contrast variance
Fix time-series metrics to use general grouping/aggregate dimension code (lag1, annual_harmonic, mae_day_max)

Speedup:
reuse same DatasetMetrics object in get_metric_label instead of creating a new object.
add flag check to nan_inf_flag, all_nan_flag conditional to prevent checking the plot_data again if flag is already set
some metrics (see lag1) take a very long time between loading data and computing a metric (up to several minutes), investigate this
Review metrics and use xarray functionality (especially shift) to improve parallelization

Memory Improvements:
Make sure all data in metrics gets removed after computing a metric (after lag1 computed ~30 GB remains in worker memory)
Make sure metrics are not recomputed in time_series plots (and histogram, periodograms)

**Comment by allibco** [comment]
memory improvements is done.
speedup is done (except last item should be checked)

Am closing this and opening a new issue with what remains
