### ISSUE TITLE
warning message in compare_stats

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#191]
../../../ldcpy/metrics.py:856: MatplotlibDeprecationWarning: You are modifying the state of a globally registered colormap. In future versions, you will not be able to modify a registered colormap in-place. To remove this warning, you can make a copy of the colormap first. cmap = copy.copy(mpl.cm.get_cmap("coolwarm"))

**Comment by allibco** [comment]
We should fix this as it's in the tutorial notebook

**Comment by allibco** [comment]
and the metrics notebook....

**Comment by allibco** [comment]
this message only occurs on Cheyenne...

**Comment by pinarda** [comment]
I did this a while back, error should be gone now...
