### ISSUE TITLE
compare stats on 3d data

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#194]
gives and error (in compare_stats) and maybe otherwise (didn't check yet(

**Comment by allibco** [comment]
only a problem via compare_stats()

**Comment by allibco** [comment]
Actually compare_stats does not work on 3D data.  How do we want to handle this?  Average over levels? Pick a level?

**Comment by allibco** [comment]
if specify a level, the just do the level - otherwise average over levels

**Comment by pinarda** [comment]
Set the default to level 0 - can be specified by named argument

**Comment by allibco** [comment]
This is still a bug.  If you call compare_stats on a 3d variable, you get an error in the ssim calculation.  I don't see that we can pass a level argument through to metrics.  So I am not sure if I should add a level argument to compare_stats, or if there is a better way ... @pinarda

**Comment by andersy005** [comment]
> I don't see that we can pass a level argument through to metrics. So I am not sure if I should add a level argument to compare_stats, or if there is a better way 

Would it be useful to use `cf-xarray` to detect the vertical dimension, and then to compute metrics for each vertical level and return a dataset/datarray of metrics for all levels?

**Comment by allibco** [comment]
Good suggestion! Thanks

**Comment by allibco** [comment]
this is fixed in my brach - but not checked in yet
