### ISSUE TITLE
Enable documentation autobuild on Readthedocs

### ISSUE THREAD

**Issue by andersy005** [NCAR/ldcpy#204]
Now that Readthedocs provides automatic build of documentation for **pull requests**: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html, it would nice to enable this feature for this repo. 

@pinarda, when you get a chance can you enable the above feature on [readthedocs](https://readthedocs.org/dashboard/ldcpy/advanced/)?

**Comment by pinarda** [comment]
Done - should be active on all new pull requests.
