### ISSUE TITLE
Support additional dataset naming schemes

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#212]
Use Cf-array package to discover names of lat, lon, time etc.

**Comment by allibco** [comment]
From @andersy005 
If you want to avoid hard-coding these for a few known cases and supporting arbitrary number of data formats from different model outputs, I highly recommend looking into cf-xarray's describe() functionality: https://cf-xarray.readthedocs.io/en/latest/examples/introduction.html#What-attributes-have-been-discovered?  


I am going to start working on this now as I need to be able to read in the ocean data...

**Comment by allibco** [comment]
conda install -c conda-forge cf_xarray

**Comment by andersy005** [comment]
@allibco, here's the code I use to get `latitude`, `longitude`, `time` and `vertical` coordinates with `cf-xarray`:

### Inspect the dataset of interest 

```python
In [19]: import xarray as xr

In [20]: import cf_xarray

In [21]: ds
Out[21]: 
<xarray.Dataset>
Dimensions:  (time: 36, x: 275, y: 205)
Coordinates:
  * time     (time) object 1980-09-16 12:00:00 ... 1983-08-17 00:00:00
    xc       (y, x) float64 ...
    yc       (y, x) float64 ...
Dimensions without coordinates: x, y
Data variables:
    Tair     (time, y, x) float64 ...
Attributes:
    title:                     /workspace/jhamman/processed/R1002RBRxaaa01a/l...
    institution:               U.W.
    source:                    RACM R1002RBRxaaa01a
    output_frequency:          daily
    output_mode:               averaged
    convention:                CF-1.4
    references:                Based on the initial model of Liang et al., 19...
    comment:                   Output from the Variable Infiltration Capacity...
    nco_openmp_thread_number:  1
    NCO:                       "4.6.0"
    history:                   Tue Dec 27 14:15:22 2016: ncatted -a dimension...

In [22]: ds.cf.describe()
Axes:
        X: []
        Y: []
        Z: []
        T: ['time']

Coordinates:
        longitude: ['xc']
        latitude: ['yc']
        vertical: []
        time: ['time']

Cell Measures:
        area: []
        volume: []

Standard Names:
```

### Getting coordinates

```python
In [23]: longitude = ds.cf["longitude"]
/Users/abanihi/opt/miniconda3/envs/geocat-comp-dev/lib/python3.8/site-packages/cf_xarray/accessor.py:1030: UserWarning: Variables {'xv'} not found in object but are referred to in the CF attributes.
  warnings.warn(

In [24]: latitude = ds.cf["latitude"]
/Users/abanihi/opt/miniconda3/envs/geocat-comp-dev/lib/python3.8/site-packages/cf_xarray/accessor.py:1030: UserWarning: Variables {'yv'} not found in object but are referred to in the CF attributes.
  warnings.warn(

In [25]: time = ds.cf["time"]

In [26]: longitude
Out[26]: 
<xarray.DataArray 'xc' (y: 205, x: 275)>
array([[189.222932, 189.389909, 189.558366, ..., 293.779061, 294.027924,
        294.274399],
       [188.712343, 188.878007, 189.045152, ..., 294.335053, 294.583375,
        294.829293],
       ...,
       [124.04724 , 123.88362 , 123.71852 , ...,  16.831718,  16.58437 ,
         16.339496],
   
Dimensions without coordinates: y, x
Attributes:
    long_name:  longitude of grid cell center
    units:      degrees_east
    bounds:     xv

In [27]: latitude
Out[27]: 
<xarray.DataArray 'yc' (y: 205, x: 275)>
array([[16.534986, 16.778456, 17.022224, ..., 27.363016, 27.11811 , 26.87289 ],
       [16.852192, 17.098089, 17.344309, ..., 27.805843, 27.557646, 27.309156],
       ...,
       [17.31179 , 17.561247, 17.811046, ..., 28.450248, 28.197183, 27.943847],
       [16.999195, 17.246229, 17.493587, ..., 28.0116  , 27.761856, 27.511827]])
Dimensions without coordinates: y, x
Attributes:
    long_name:  latitude of grid cell center
    units:      degrees_north
    bounds:     yv

In [28]: time
Out[28]: 
<xarray.DataArray 'time' (time: 36)>
array([cftime.DatetimeNoLeap(1980, 9, 16, 12, 0, 0, 0),
       cftime.DatetimeNoLeap(1980, 10, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1980, 11, 16, 12, 0, 0, 0),
       cftime.DatetimeNoLeap(1980, 12, 17, 0, 0, 0, 0),
       cftime.DatetimeNoLeap(1981, 1, 17, 0, 0, 0, 0),
       ...
       cftime.DatetimeNoLeap(1983, 8, 17, 0, 0, 0, 0)], dtype=object)
Coordinates:
  * time     (time) object 1980-09-16 12:00:00 ... 1983-08-17 00:00:00
Attributes:
    long_name:       time
    type_preferred:  int
```

### Getting coordinate names:

```python
In [29]: time.name
Out[29]: 'time'

In [30]: longitude.name
Out[30]: 'xc'

In [31]: latitude.name
Out[31]: 'yc'
```

**Comment by allibco** [comment]
thank you - I was just reading the cf-array introduction right now

**Comment by allibco** [comment]
@andersy005 
For your example above, if you were to do 
vert = ds.cf["vertical"]
Then you get an error since there is not vertical coord here (but if there was, then is completes successfully...)

So what is the suggested way to know if there is a vertical coord? (WIthout an error)```
I know that I could do:
if "lev" in ds.keys():
        print("yes")
else:
        print("no")

But then I am assuming the name "lev".  It looks like cf.describe() does not return an object that I can search?

**Comment by allibco** [comment]
Also just adding this here, for pop data we have two. options for lat and lon, e.g.:

pop_sst.cf.describe()
Axes:
	X: []
	Y: []
	Z: []
	T: ['time']

Coordinates:
	longitude: ['TLONG', 'ULONG']
	latitude: ['TLAT', 'ULAT']
	vertical: []
	time: ['time']

Cell Measures:
	area: []
	volume: []

Standard Names:

**SO you cannot do: latitude = pop_sst.cf["latitude"]
(you can do pop_sst.cf[["latitude"]], but you get a list of 2 choices...

**Instead, get the relavant coord for the specific variable - here for SST:
latitude = pop_sst.SST.cf["latitude"]
note: can also do latitude = pop_sst.SST.cf.describe()

**Comment by andersy005** [comment]
> So what is the suggested way to know if there is a vertical coord? (WIthout an error)

How about a `try except` block:

```python
In [7]: try:
   ...:     vert = ds.cf["vertical"]
   ...: except KeyError:
   ...:     vert = None
   ...: 

In [8]: vert
```


Once you have `vert`, you could then check if it's not None and proceed with the logic for when you have / doesn't have the vertical coordinate:

```python
In [9]: vert is None
Out[9]: True
```

**Comment by allibco** [comment]
Ahhh - got it - thanks.

**Comment by andersy005** [comment]
> Also just adding this here, for pop data we have two. options for lat and lon, e.g.:

> ```python
> pop_sst.cf.describe()
> Axes:
> X: []
> Y: []
> Z: []
> T: ['time']
> 
> Coordinates:
> longitude: ['TLONG', 'ULONG']
> latitude: ['TLAT', 'ULAT']
> vertical: []
> time: ['time']
> 
> Cell Measures:
> area: []
> volume: []
> ```
> 
> Standard Names:
> 
> **SO you cannot do: latitude = pop_sst.cf["latitude"]
> (you can do pop_sst.cf[["latitude"]], but you get a list of 2 choices...

Ccing @dcherian. Any ideas on what to do here? :)

**Comment by dcherian** [comment]
Nice to see people using cf-xarray! Please open issues for bugs and feature requests.

> So what is the suggested way to know if there is a vertical coord?

`"vertical" in ds.cf` should tell you this. 

> or pop data we have two. options for lat and lon, e.g.

The `SST` DataArray should have `.attrs["coordinates"] = "TLONG TLAT"`, if not that needs to be fixed. What does the repr for `pop_sst` look like?

**Comment by allibco** [comment]
@dcherian I'll open an issue for this, but ds.cf["vertical"] returns an error if there is not vertical coordinate (so for 2D variables)

Right...since the pop data has multiple lat and lons, then for POP data I have to include the variable name to get the one that I want:
latitude = pop_sst.SST.cf["latitude"]

Whereas for cam data, I can just do without the variable name:
latitude = cam_ts.cf["latitude"]

So since I will not know what type of file this is (cam or pop), then I suppose I should just always use the variable name (so do latitude = cam_ts.TS.cf["latitude"] for cam also)

**Comment by dcherian** [comment]
> I should just always use the variable name

:+1: Yes, this is the direct way of getting lats and lons associated with a variable.
