### ISSUE TITLE
compare stats: why do we need aggregate_dims=['lat', 'lon']?

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#216]
In the tutorial NB, for example, we have in "In [4]":

```python
# print 'TS' statistics about 'orig', 'zfpA1.0', and diff between the two datasets
# for time slice = 0
ds = col_ts.isel(time=0)
ldcpy.compare_stats( ds, "TS", "orig", "zfpA1.0", aggregate_dims=['lat', 'lon'])
```
I don't  know why we need the  aggregate_dims argument (seems like we get the same answer without it).  SInce there is only one time slice, then isn't this kind of assumed?  If we do need it, we should explain in the tutorial text.  

(Also it is in the MetricsNotebook a number of times.....)

@andersy005 maybe you can explain?

**Comment by andersy005** [comment]
> I don't know why we need the aggregate_dims argument (seems like we get the same answer without it). SInce there is only one time slice, then isn't this kind of assumed?

You're right. We don't need to pass ` aggregate_dims=['lat', 'lon']`. With this line 

https://github.com/NCAR/ldcpy/blob/43518e22be4b6d99b5eadb999ddc8d839f903f5f/ldcpy/util.py#L167

we end up passing `aggregate_dims=None` to `DatasetMetrics` class. With `aggregate_dims=None`, xarray collapses all dimensions during the aggregations:

`ds.mean(None)` ---> `ds.mean(dims=xr.ALL_DIMS)`

We should update the notebook (by removing `aggregate_dims=['lat', 'lon']).

**Comment by andersy005** [comment]
@allibco, thank you for your patience! I just realized that this issue is a week old. It appears that I missed the notification for this issue (I may have archived the notification by mistake :( )

**Comment by allibco** [comment]
@andersy005 - no worries! Thanks for the explanation.

I will update the notebooks.
