### ISSUE TITLE
test against upstream development versions

### ISSUE THREAD

**Issue by dcherian** [NCAR/ldcpy#233]
It'd be nice if you could test against development versions of upstream packages like xarray & cf_xarray (and more?). It'll help everyone catch bugs early

cc @andersy005

**Comment by allibco** [comment]
Can one of you explain to me what "test against upstream development" means? Thanks :)

**Comment by dcherian** [comment]
runs the tests in a an environment where pip installs dependencies from git. So you test the latest unreleased changes, to catch bugs. Really helps upstream projects like xarray / cf-xarray.

**Comment by allibco** [comment]
I see - thanks!
