### ISSUE TITLE
figure out why "ds" output looks different when notebook is cloned and before rerunning the code

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#57]

**Comment by pinarda** [comment]
if we use notebook viewer this may not be a problem.

**Comment by allibco** [comment]
Another idea is to use ds.info() instead of ds - that might look cleaner

**Comment by pinarda** [comment]
looks to have been a bad commit, they are identical now.

ds prints in a nice table now, while ds.info formats the information like so:

ds.info()

xarray.Dataset {
dimensions:
	collection = 3 ;
	ilev = 31 ;
	lat = 192 ;
	lev = 30 ;
	lon = 288 ;
	nbnd = 2 ;
	time = 100 ;

variables:
	object time_bnds(time, nbnd) ;
		time_bnds:long_name = time interval endpoints ;
	float64 hyai(ilev) ;
		hyai:long_name = hybrid A coefficient at layer interfaces ;
	float64 hybm(lev) ;
		hybm:long_name = hybrid B coefficient at layer midpoints ;
	float64 hybi(ilev) ;
		hybi:long_name = hybrid B coefficient at layer interfaces ;
	float64 gw(lat) ;
		gw:long_name = gauss weights ;
	float64 hyam(lev) ;
		hyam:long_name = hybrid A coefficient at layer midpoints ;
	float64 P0() ;
		P0:long_name = reference pressure ;
		P0:units = Pa ;
	float64 lon(lon) ;
		lon:long_name = longitude ;
		lon:units = degrees_east ;
	float64 ilev(ilev) ;
		ilev:long_name = hybrid level at interfaces (1000*(A+B)) ;
		ilev:units = level ;
		ilev:positive = down ;
		ilev:standard_name = atmosphere_hybrid_sigma_pressure_coordinate ;
		ilev:formula_terms = a: hyai b: hybi p0: P0 ps: PS ;
	float64 lev(lev) ;
		lev:long_name = hybrid level at midpoints (1000*(A+B)) ;
		lev:units = level ;
		lev:positive = down ;
		lev:standard_name = atmosphere_hybrid_sigma_pressure_coordinate ;
		lev:formula_terms = a: hyam b: hybm p0: P0 ps: PS ;
	float64 lat(lat) ;
		lat:long_name = latitude ;
		lat:units = degrees_north ;
	object time(time) ;
		time:long_name = time ;
		time:bounds = time_bnds ;
	float32 TS(collection, time, lat, lon) ;
		TS:units = K ;
		TS:long_name = Surface temperature (radiative) ;
		TS:cell_methods = time: mean ;
	<U8 collection(collection) ;

// global attributes:
	:Conventions = CF-1.0 ;
	:source = CAM ;
	:case = b.e11.B20TRC5CNBDRD.f09_g16.030 ;
	:title = UNSET ;
	:logname = mai ;
	:host = ys0110 ;
	:Version = $Name$ ;
	:revision_Id = $Id$ ;
	:initial_file = b.e11.B20TRC5CNBDRD.f09_g16.001.cam.i.1920-01-01-00000.nc ;
	:topography_file = /glade/p/cesmdata/cseg/inputdata/atm/cam/topo/USGS-gtopo30_0.9x1.25_remap_c051027.nc ;
	:history = Wed Oct 16 12:10:39 2019: ncks -d time,0,99,1 -v TS,gw,lat,lon,lev b.e11.B20TRC5CNBDRD.f09_g16.030.cam.h1.TS.19200101-20051231.nc orig.TS.100days.nc
Wed Oct 29 04:21:35 2014: ncks -F -d time,1,31390 b.e11.B20TRC5CNBDRD.f09_g16.030.cam.h1.TS.19200101-20051231.nc S_b.e11.B20TRC5CNBDRD.f09_g16.030.cam.h1.TS.19200101-20051231.nc ;
	:NCO = netCDF Operators version 4.7.9 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco) ;
}

This might reduce the total information output, but I am not sure it looks any cleaner. Closing for now.

**Comment by allibco** [comment]
or use:
xr.set_options(display_style="html")

**Comment by allibco** [comment]
never mind - i think html is the default...

**Comment by pinarda** [comment]
We should probably make a new issue for this if we want to change the formatting or what information is printed - the original issue appears to be fixed
