### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by pinarda** [NCAR/ldcpy#80]
Limit on PyPI is 100MB, data files are currently using 443 MB and the rest of the package is 3.1MB. We probably want to  removing datafiles like the cam-se data, and reduce the number of time slices on the rest of the data. Also, rename the data directory sample-data

**Comment by allibco** [comment]
I checked and many other packages have data - it's just much smaller.  I can make smaller files this afternoon hopefully :)

**Comment by pinarda** [comment]
Great! the pipeline is all set up so we should be able to upload v0.1 to PyPI and simplify the installation steps quite a bit!
