### ISSUE TITLE
trouble installing cartopy with user instructions

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#88]
Here's my output below.  I am wondering if the issue is related to the environment that I do the conda update  and pip update in is python 3.7 ?

(base) cisl-duluth:ldcpy abaker$ conda update conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/abaker/anaconda3

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    lazy-object-proxy-1.5.0    |   py37haf1e3a3_0          29 KB
    ------------------------------------------------------------
                                           Total:          29 KB

The following packages will be REMOVED:

  typed-ast-1.4.1-py37h1de35cc_0

The following packages will be UPDATED:

  lazy-object-proxy                    1.4.3-py37h1de35cc_0 --> 1.5.0-py37haf1e3a3_0
  wrapt                               1.11.2-py37h1de35cc_0 --> 1.12.1-py37h1de35cc_1

The following packages will be DOWNGRADED:

  astroid                                      2.4.2-py37_0 --> 2.3.3-py37_0
  pylint                                       2.5.3-py37_0 --> 2.4.4-py37_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
lazy-object-proxy-1. | 29 KB     | ############################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) cisl-duluth:ldcpy abaker$ pip install --upgrade pip
Requirement already up-to-date: pip in /Users/abaker/anaconda3/lib/python3.7/site-packages (20.1.1)
(base) cisl-duluth:ldcpy abaker$ python --version
Python 3.7.4
(base) cisl-duluth:ldcpy abaker$ conda info --envs
# conda environments:
#
base                  *  /Users/abaker/anaconda3
dask-tutorial            /Users/abaker/anaconda3/envs/dask-tutorial
geocat-examples          /Users/abaker/anaconda3/envs/geocat-examples
ldcpy_dev                /Users/abaker/anaconda3/envs/ldcpy_dev
ldcpy_orig               /Users/abaker/anaconda3/envs/ldcpy_orig
mypy3                    /Users/abaker/anaconda3/envs/mypy3
py372                    /Users/abaker/anaconda3/envs/py372
xarray                   /Users/abaker/anaconda3/envs/xarray

(base) cisl-duluth:ldcpy abaker$ conda create --name ldcpy python
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/abaker/anaconda3/envs/ldcpy

  added / updated specs:
    - python

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2020.6.24-0
  certifi            pkgs/main/osx-64::certifi-2020.6.20-py38_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20191231-h1de35cc_1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1g-h1de35cc_0
  pip                pkgs/main/osx-64::pip-20.1.1-py38_1
  python             pkgs/main/osx-64::python-3.8.3-h26836e1_2
  readline           pkgs/main/osx-64::readline-8.0-h1de35cc_0
  setuptools         pkgs/main/osx-64::setuptools-49.1.0-py38_0
  sqlite             pkgs/main/osx-64::sqlite-3.32.3-hffcf06c_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  wheel              pkgs/main/osx-64::wheel-0.34.2-py38_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate ldcpy
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) cisl-duluth:ldcpy abaker$ condda activate ldcpy
-bash: condda: command not found
(base) cisl-duluth:ldcpy abaker$ conda activate ldcpy
(ldcpy) cisl-duluth:ldcpy abaker$ conda install cartopy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                    

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - cartopy -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

(ldcpy) cisl-duluth:ldcpy abaker$ python --version
Python 3.8.3

**Comment by allibco** [comment]
maybe i should update my base conda to 3.8?

**Comment by allibco** [comment]
The title should say "cartopy" not "anaconda" :)

**Comment by pinarda** [comment]
my base conda is also using python version 3.7.7, and everything still installs correctly for me. @allibco can you try creating the environment with the following line instead and see if anything changes?

`conda create --name ldcpy python`

**Comment by allibco** [comment]
(base) cisl-duluth:testing abaker$ conda --version
conda 4.8.3

**Comment by allibco** [comment]
I did "conda create --name ldcpy python=3.7" and it worked! (The installation, that it...)

**Comment by pinarda** [comment]
Instructions have changed since ldcpy has been added to conda-forge. We should not encounter this issue any longer.
