### ISSUE TITLE
example with AWS data

### ISSUE THREAD

**Issue by allibco** [NCAR/ldcpy#98]
http://ncar-aws-www.s3-website-us-west-2.amazonaws.com/CESM_LENS_on_AWS.htm

https://github.com/NCAR/cesm-lens-aws

Allison will find out about adding orig version of 31 & 33 to AWS

**Comment by allibco** [comment]
The data should be on AWS next week!  I just dis monthly and daily for ensemble 31...

**Comment by pinarda** [comment]
I assume they are going to be added to the catalog here when they are on AWS? Probably as aws-cesm1-cam5.csv.gz?


Below is the code to read in a dataset assuming the above is correct:

# open the datastore
col = intake.open_esm_datastore("https://raw.githubusercontent.com/NCAR/cesm-lens-aws/master/intake-catalogs/aws-cesm1-cam5.json")
col

#search for a dataset
col_subset = col.search(experiment="RCP85", frequency="monthly", variable=["TS"])
col_subset.df.head()

#selects dataset

**Comment by allibco** [comment]
s3://ncar-cesm-lens-baker-lossy-compression-test
